#!/bin/bash
#5	Написать скрипт, находящий в заданном каталоге и всех его подкаталогах все файлы, владельцем которых является заданный пользователь.
#Имя владельца и каталог задаются пользователем в качестве первого и второго аргумента командной строки. 
#Скрипт выводит результаты в файл (третий аргумент командной строки) в виде полный путь, имя файла, его размер.  
#На консоль выводится общее число просмотренных файлов

set -eu

if [[ "$#" -ne 3 ]]; then
  echo "Invalid number of arguments" >&2
  exit 1
fi

target_owner=${1}
src_dir=${2}
output_file=${3}

rm ${output_file}
if ! id "${target_owner}" &> /dev/null; then
  echo "User '${target_owner}' not found" >&2
  exit 1
fi

if [[ ! -d ${src_dir} ]]; then
  echo "Source folder '${src_dir}' does not exist" >&2
  exit 1
fi

find "${src_dir}" -user "${target_owner}" -type f -exec readlink -f {} \; | xargs ls -l | awk '{ print $9"\t"$5 }' > "${output_file}"
find "${src_dir}" -type f | wc -l





